
[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 9.5

[font.bold]
family = "Fira Code Nerd Font"
style = "SemiBold"

[font.bold_italic]
family = "Fira Code Nerd Font"
style = "SemiBold"

[font.italic]
family = "Fira Code Nerd Font"
style = "Light"

[font.normal]
family = "Fira Code Nerd Font"
style = "Retina"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/themes/prefer-dark.toml"
]
