live_config_reload = true

import = [
  "~/.config/alacritty/themes/prefer-dark.toml"
]


#[colors.bright]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[colors.normal]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[colors.primary]
#background = "#ffffff"
#foreground = "#000000"
##background = "#000000"
##foreground = "#ffffff"

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "Fira Code"
style = "SemiBold"

[font.bold_italic]
family = "Fira Code"
style = "SemiBold"

[font.italic]
family = "Fira Code"
style = "Light"

[font.normal]
family = "Fira Code"
style = "Retina"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.9
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2
