live_config_reload = true

[colors.bright]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#dfddc8"
yellow = "#dfa000"

[colors.normal]
black = "#5c6a72"
blue = "#3a94c5"
cyan = "#35a77c"
green = "#8da101"
magenta = "#df69ba"
red = "#f85552"
white = "#dfddc8"
yellow = "#dfa000"

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "Fira Code"
style = "SemiBold"

[font.bold_italic]
family = "Fira Code"
style = "SemiBold"

[font.italic]
family = "Fira Code"
style = "Light"

[font.normal]
family = "Fira Code"
style = "Retina"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[schemes.black_on_white.bright]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"

#[schemes.black_on_white.normal]
#black = "#5c6a72"
#blue = "#3a94c5"
#cyan = "#35a77c"
#green = "#8da101"
#magenta = "#df69ba"
#red = "#f85552"
#white = "#dfddc8"
#yellow = "#dfa000"
#
#[schemes.black_on_white.primary]
#background = "#ffffff"
#foreground = "#000000"
#
#[schemes.white_on_black.bright]
#black = "0x002b36"
#blue = "0x839496"
#cyan = "0x93a1a1"
#green = "0x586e75"
#magenta = "0x6c71c4"
#red = "0xcb4b16"
#white = "0xfdf6e3"
#yellow = "0x657b83"
#
#[schemes.white_on_black.normal]
#black = "0x073642"
#blue = "0x268bd2"
#cyan = "0x2aa198"
#green = "0x859900"
#magenta = "0xd33682"
#red = "0xdc322f"
#white = "0xeee8d5"
#yellow = "0xb58900"
#
#[schemes.white_on_black.primary]
#background = "0x001b26"
#foreground = "0xe3e4e6"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.9
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2
