sudo pacman --noconfirm -S\
    alacritty\
    tmux\
    fish\
    firefox\
    neovim\
    lua-language-server\
    rust-analyzer\
    docker\
    docker-compose\
    rustup\
    yarn\
    dbeaver\
    postgresql\
    sqlx-cli\
    ttf-fira-sans\
    ttf-fira-code\
    noto-fonts-cjk\
    exa\
    bat\
    transmission-cli\
    ripgrep\
    wl-clipboard\
    xclip\
    dnsmasq\
    gimp\
    htop
